image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # install eslint-config-defaults
    - npm install --save eslint-config-defaults
    # install @ljharb/eslint-config module
    - npm install --save @ljharb/eslint-config
    # Run ESLinit
    - eslint "."

