concurrent = 0

[[runners]]
  name = ""
  url = "https://CI/"
  token = "TOKEN"
  limit = 0
  output_limit = 1000
  executor = ""
  builds_dir = ""
  shell = ""
  environment = ["ENV=value", "LC_ALL=en_US.UTF-8"]
  disable_verbose = false


